# Generated by Django 3.1 on 2020-08-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date']},
        ),
    ]
