# Generated by Django 3.1 on 2020-08-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200824_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
